DROP TABLE IF EXISTS sys_user;

CREATE TABLE sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sys_user_email UNIQUE (email)
);

INSERT INTO sys_user (name, email, status, created_at, updated_at)
VALUES ('测试用户', 'test@selfsp.local', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
